apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: observability

data:
  otel-collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      # TRACES → TEMPO
      otlp/tempo:
        endpoint: tempo.tracing.svc.cluster.local:4317
        tls:
          insecure: true

      # METRICS → PROMETHEUS (via remote_write)
      prometheusremotewrite:
        endpoint: http://mimir.monitoring.svc.cluster.local:9009/api/v1/push

      # LOGS → LOKI
      loki:
        endpoint: http://loki.loki.svc.cluster.local:3100/loki/api/v1/push

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/tempo]

        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [prometheusremotewrite]

        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [loki]
