spring.application.name=spring-boot-otel
server.port=8081
management.endpoints.web.exposure.include=*
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs
management.tracing.sampling.probability=1.0
management.otlp.metrics.export.step=10s

# Delta temporality voor histogram compatibiliteit met Elasticsearch OTel mode
otel.exporter.otlp.metrics.temporality.preference=delta

#management.tracing.export.enabled=false
#management.logging.export.otlp.enabled=false
#management.otlp.metrics.export.enabled=false
#management.opentelemetry.logging.export.enabled=false

otel.metrics.exporter=none

#logging.level.root=INFO
#logging.level.org.apache.camel=DEBUG
#logging.level.io.micrometer.core.instrument=DEBUG
#logging.level.org.apache.camel.component.micrometer=DEBUG
#logging.level.io.opentelemetry.exporter=DEBUG