apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir
  namespace: metrics
spec:
  serviceName: mimir
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
        - name: mimir
          image: grafana/mimir:2.11.0
          args:
            - -config.file=/etc/mimir/mimir.yaml
          ports:
            - containerPort: 9009
          volumeMounts:
            - name: config
              mountPath: /etc/mimir
            - name: data
              mountPath: /data

      volumes:
        - name: config
          configMap:
            name: mimir-config
        - name: data
          emptyDir: {}