apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
  namespace: tracing
spec:
  serviceName: tempo
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:2.5.0
          args:
            - "-config.file=/etc/tempo/tempo.yaml"
          ports:
            - containerPort: 3200
            - containerPort: 4317
            - containerPort: 4318
          volumeMounts:
            - name: config
              mountPath: /etc/tempo
            - name: data
              mountPath: /tmp/tempo

      volumes:
        - name: config
          configMap:
            name: tempo-config
        - name: data
          emptyDir: {}
