apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-server-config
  namespace: elastic
data:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"

    output.elasticsearch:
      hosts: ["http://elasticsearch:9200"]
      username: "elastic"
      password: "${ELASTIC_PASSWORD}"

    setup.kibana:
      host: "http://kibana:5601"
