apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: elastic
type: Opaque
stringData:
  elastic-password: "elastic12!"
  kibana-system-password: "kibanasystem12!"

---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-certificates
  namespace: elastic
type: Opaque
stringData:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFCzCCAvOgAwIBAgIUE6VpGadahRS5j2zOCYWmYEQXh6EwDQYJKoZIhvcNAQEL
    BQAwFTETMBEGA1UEAwwKZWxhc3RpYy1jYTAeFw0yNjA2MDIxODU0MTNaFw0zNjA1
    MzAxODU0MTNaMBUxEzARBgNVBAMMCmVsYXN0aWMtY2EwggIiMA0GCSqGSIb3DQEB
    AQUAA4ICDwAwggIKAoICAQDmOPGVdWChzuPcpXxM4kKKlm3cep6ArLR72qmFdmCg
    K9Kr2KEcqRizMCdG9loDQTQDgwjWg8m4AwbwxAmBzhqvcNIaA6gggR7+GP9NkktL
    ylG/i3PNJH2mv77ZR54bfh3f8Cw9DeRLd+NbvCj38fR3TRAjDAOf9wLfJYxSMkIt
    pmYiwmjXT8e/IMZl2mDVULPbAEXrQUYzYvBw9znjSHPWziSv+HD0G5KfSQA4BvG2
    OrE3na4G3HYyoxOd8KcooBAF/qFblWyrsSfGuMZr+HQg738KdYH1DZ03aC67ege3
    Ja1HfDIryAHfJDlIGVEv6tZthTG6Z7qYwyYoXR8DynuHksgptfnzbAHhr9Tm1hiM
    VHjqSjVLsM8GqIGafpKMBWk3x8a3p8/2hzYChcpGfwg0uHZEs+tcxLfwTrJ/4Oyl
    Z2IblwaUn6e1Q8f+Tqutobqlh6Eywp1Dly05E3fGSPiUPXFQkBkcazyQEzwU+8Al
    hc+5Cen2UyEmXcuYkspDBh9bamDYSmzcFWzXfgXMxtPisS1hR30/qBcvG7yBwiX6
    1BlwTbJrgTdcRHootofk3EV6F18VJDAeN/zJrapJBp+VgKob9WfInxoHJpEzOyVs
    7kfqyEOyLg0/r+evW9ME3mDrxeThzNgKji08ULE8Iyu2Bv9mcs7K9m4jYigjmcc8
    hwIDAQABo1MwUTAdBgNVHQ4EFgQU+fRyC8aeQU2uz4BO84R5NDFbzhAwHwYDVR0j
    BBgwFoAU+fRyC8aeQU2uz4BO84R5NDFbzhAwDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAgEAEJv8syZ7KWqv2LdRvmH10PtmNd//wmL7duIBccQG67XT
    IRWruXyi+OMB+i8y5eWSxcvzjL1mPDwrtlm6cQFXwBW41yHx3fOazXsj0MOchqdE
    /Iy/iVv+KoKyAAgRTxgcaH2jcjoUnDThJWvl2s5Tc5iRmSIdrE0MXecdavkCr4cC
    /XZKdsbBsAXPauAOUxqS/f1gNDoa5dNM7Tl6LwrfXGpgVcCiqM8/ugXZtzRxaBcC
    uEE596tqrkHU0H0f1xAP06N+zxMuit2IMnaPumdPq/gMo6jxo4M+ipQt/ikrERqc
    3uLnArsdxQB5fcYbPL6cyuPsQtcTq8msVMekJQAS13tYLqYUaNSjRfCYrFcyK0Jm
    EJoiLWJ0P5lOxsjXfjJWkeipqw4ApzfvgWIgQ8Nj6neFTXxVoqHD2jR/7qDqMtBH
    I9fnESHeP7FJiTpTUCAY0wXbnIFYTv9vfIHPtYM0CNNshPBPCBAW/hFgFKEQXvlA
    UekwC4SScLTLoMuEOiLIOdW+IkVotEQUqFGEvftgMJPvC7hlbNM4p8Wvc5L/iEDq
    2wwkWxwnJiTI4AQLSolK4gGsGd+MXU69nQifzlLgUu01mNhTR1WOYThJmVbLjyF5
    vhKO7ApHX0G97r5Fl7NLD5wRBBe2Q6QlNC6Oy4DYDeY6E0FG2cDUveL51rFDHvI=
    -----END CERTIFICATE-----
  node.crt: |
    -----BEGIN CERTIFICATE-----
    MIID/TCCAeWgAwIBAgIUAeImsMkPSRzfoiGrc4PV8HSVeHowDQYJKoZIhvcNAQEL
    BQAwFTETMBEGA1UEAwwKZWxhc3RpYy1jYTAeFw0yNjA2MDIxODU5NTdaFw0yODA5
    MDQxODU5NTdaMBgxFjAUBgNVBAMMDWVsYXN0aWNzZWFyY2gwggEiMA0GCSqGSIb3
    DQEBAQUAA4IBDwAwggEKAoIBAQCRrtQJp1+bi7yGpLWzfFdh++YxLSQiNamsmPvF
    G9TPueVj6/h0Zi/Sf6qTxWJjE791iSo1wDbuLx9T2INij8hL3JyW+8CljewUJ17r
    aExrw99v5GVvn7v8cK8xnqUnLbpmUTTgYibf+U2/NFm6KyVyfFCoF1Y8qX7Z0P9e
    zkFVoCjknnG9C7PtmYJ3bEqUD8YgjWG6Ikr70jJg3KFe5r8awePIKuH/hQ6fK0VP
    0ULRGjUD+BHivsyE+IbD5XYFFfY6IyZC9hO1YYNhbMRcKkL9FUpr1XzrE4uNV6Jl
    3lgfeGVo4mBMCLVVOFYCS1OKyHWJ4YIPW/bUgFktaavzkV7jAgMBAAGjQjBAMB0G
    A1UdDgQWBBTbxdTPvE96mcFu5VAr6+eVC/jmpDAfBgNVHSMEGDAWgBT59HILxp5B
    Ta7PgE7zhHk0MVvOEDANBgkqhkiG9w0BAQsFAAOCAgEAlNQLGfHSszhucJWkrGzu
    bDV3RMaIXw1MfSKOvk6nvt8Tg4pd1DMNlWD5CvANplzrVi/AHJOFSzeL+vj06wYx
    NJugEn5rGzNpqch5NPduB8DmTxegdiVWLj3kkp7qrtqtvGNhPNFy5Tk5nmAlKU3j
    5ekpisJtyeCAqJE93Mf93fZIehOuY5SRCw1K5608f9HSPQUpQ+wm24yT9swDd3VJ
    x0r2Z6Ui+kCFIsRAq/oPQv/7+lgUPjzARRDwHT5MC/N8x/2Cr5KoJoafhE4nvgcy
    WsWd5SE4g23S8Nq/NfwaP/DqFXH6WMkQna1Oc8hJpcWCbh3nViiBSewVaJKhtfZK
    p80DYRi3uW9aAsFu1h9e/j7WNZa/X6ZvPOpEvC+cE0WyczZdkU7Hr7X8+i3bvuGo
    46Brx3b9lYzg74Db7TFTK5ihaW1RCcwVOs9FqXKtwqd9DntQJkF38t3HoIxdt0AT
    EYNB5LxhZEGGMkDGycRfJ/mb/Pm98y83xJ2uYQtw3ZDfqp7H7uOAovEzmkE+PF/s
    NZuBHM6DlZ+bQ6kM8RPWg9aPv1mrW95JX18t4tIzmf62o6gz6j4fU3obVCmwcngz
    9O+hN3VbzImebJrmSrvM+lPltTDkQ27bZF5u6/EIv1qwJQK1dCZXykGcm8CpWvir
    VYU8ON3xhzUprBzllAwDONU=
    -----END CERTIFICATE-----
  node.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCRrtQJp1+bi7yG
    pLWzfFdh++YxLSQiNamsmPvFG9TPueVj6/h0Zi/Sf6qTxWJjE791iSo1wDbuLx9T
    2INij8hL3JyW+8CljewUJ17raExrw99v5GVvn7v8cK8xnqUnLbpmUTTgYibf+U2/
    NFm6KyVyfFCoF1Y8qX7Z0P9ezkFVoCjknnG9C7PtmYJ3bEqUD8YgjWG6Ikr70jJg
    3KFe5r8awePIKuH/hQ6fK0VP0ULRGjUD+BHivsyE+IbD5XYFFfY6IyZC9hO1YYNh
    bMRcKkL9FUpr1XzrE4uNV6Jl3lgfeGVo4mBMCLVVOFYCS1OKyHWJ4YIPW/bUgFkt
    aavzkV7jAgMBAAECggEAEUWjCgn4Ad8NWQFKMZ96VLmizw3FDPFDzpzMrM/h6Ubm
    9XPSnypGXTSZqq9qPMjomCzM/lZtrMuVcUFoQlU9sBDV1+i9LGOpK7KHRG23Mcel
    RATWKefMR9+sRbvDZOO9B8h09m1son1SRGsWgEYBSJOIlIU/yi1mRrjKrhjSEi6f
    EkZqEKZmiX39h0aUT8+pEeKhyCzkZfZvFEJXLJ/qwttdAseYxGXXlNA60ba62TKB
    x/9EgUXuzFoQ+gcJ3QWM+Oxgm9V6kdF2Ls0WE84epCN3C0rfdTy/QKf30JNrVPWP
    Thzr2ceWWQYjdXwE1ujEyfLU/sL6UAZZop8MHgjvsQKBgQDKj/9PrNnxSpka+v/X
    peeGBt0WFtkmlFtuc6wRtr/LrUkWvvqwSFl1FRTx178iNpJd3OqN9GPVair6Z8lH
    PEtx0ddyKShxu9++1RHKdxxoG47yVKJ3jaJcjMEkuFaN7aP2qpi5doURKlPxozxx
    wLbHkd+POM9oKSHb8Biz+AKxVQKBgQC4HXwhw73QFS3nWHETPRmG4s7yhZxp9eZ8
    73MAXtdvvrc1FBtSEeMM9wRZVeLtq2u8tla1Iuy4sXme8F9EVHDVxX3uNnbm/UMJ
    RH0UnlfGHZ32FKHUqlWOxEETgQLRXVtPUor0TYbMzeYnwsYO1KAFhNYp35PWEOQA
    qr6XvbavVwKBgAf6Nc7YetjS3EbAvdSrVvvjR0+4ZKLtUtB9w7gK33DRCUDZEpxg
    rQ08YE/J9GAPkCIcMiyXBFuCS+ECt12T1VDNN9PqJQqdoIkucP3tRPQgqbeHd8KH
    lG5aqLyeeeIrCrsLKuqa7VCovxeUGyxLr6caapiEXz615/x2bzKfQNPlAoGAZsj3
    IrZvQjqArPW/8riahqYaWGRlBPalnTvkXOGVrimvh+9YrUGVGwjQIbuD+6FGfUzi
    LS95LkbOGgAhfzkQ4RbnDdTUHnJnOUZF+fvIDq88H0Q3cE1DhHdlySit1QokTq1L
    K8YYKkAMbEgdX+wuBca59Rh/JPO7BfBMhNQBp/MCgYAdjg1ctLb6G6GmI22xFTfw
    8oS3/J+5VOyO6R7wl3ckFk1afANxsGRJBBvhgnbLFNIaQaaxD0zvafbwl4EMW1YP
    hIb6oTARExABZWTyGZnp9XFfvyJDdQkQkZuiUTmU26R3lWC3Qbz6fIHTbsOYVubC
    sK4OikV2C9R4aZ75a4igkA==
    -----END PRIVATE KEY-----